apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "testapp.fullname" . }}
  labels:
    {{- include "testapp.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: frontend
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
            