name: Build and push the latest build to production

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          ecr: auto
          logout: true
          
      - name: Build and push production image
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: ${{secrets.ACR_NAME}}/testapp-website:latest
